# -*- coding: utf-8 -*-
"""00_PyTorchfundementals.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HjdTPuA2hlZvIZWL0NCTa9gKgJIHTRxn
"""

import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

"""## Introduction to tensors



### Creating tensors


"""

# scalar
 scalar = torch.tensor(7)
 scalar

scalar.ndim

#get tensor back as pyhton int
scalar.item()

# Vector
vector = torch.tensor([7,7])
vector

vector.ndim

vector.shape

# matrix
MATRİX = torch.tensor([[7,8],
                       [9,10]])
MATRİX

MATRİX.ndim

MATRİX[1]

MATRİX.shape

# TENSOR
TENSOR = torch.tensor([[[1,2,3],
                     [3,9,1],
                      [2,5,7]]])
TENSOR

TENSOR.ndim

TENSOR.shape

TENSOR[0]

print( TENSOR.numel())

"""### Random TENSORS

"""

#  Create random tensor of size (3,4)
random_tensor = torch.rand(3,4)

random_tensor

random_tensor.ndim

"""Random TENSORS"""

# Create a random tensor with similar shape of image tensor
random_image_size_tensor = torch.rand((224,224,3)) #height,width,colour channels (R,G,B)
random_image_size_tensor.shape ,random_image_size_tensor.ndim

random_image_size_tensor

### zeroos and ones

# Create a tensor of all zeros
zeros = torch.zeros(size= (3,4));
zeros

zeros * random_tensor

ones = torch.ones(size=(3,4))
ones

ones*random_tensor

ones.dtype

random_tensor.dtype

### Creating a range tensors and tensors like

# use torch.range() and değrecated message,use torch.arange()
one_to_ten = torch.arange(start = 1, end = 11,step= 1)

#Creating tensors like
ten_zeros = torch.zeros_like(input =one_to_ten)
ten_zeros

###tensor datatypes

#float 32 tensor
float_32_tensor = torch.tensor([[[1,2,3],
                               [3,9,1],
                               [2,5,7]]],
                               dtype=None,#what datatype is tensor
                                device=None,#what device is your tensor on
                                requires_grad=False)#whether or mnot yo track gradients of a tensor

float_32_tensor

float_16_tensor = torch.tensor([3.0,6.0,9.0],
                              dtype = torch.float16,
                              device = "cpu",
                              requires_grad = False)

float_16_tensor

float_162_tensor = float_32_tensor.type(torch.float16)

float_162_tensor

float_16_tensor * float_32_tensor

some_tensor= torch.rand(2,5)
some_tensor

print(some_tensor)
print(f"Datatype of tensor : {some_tensor.dtype}")
print(f"Shape of tensor : {some_tensor.shape} ")
print(f"Device of tensor : {some_tensor.device}")

""" Tensor Operation

"""

# Commented out IPython magic to ensure Python compatibility.
# %%time
# tensor = torch.tensor([1,2,3])
# torch.matmul(tensor,tensor)

"""Find the positional min and max
  
"""

y = torch.tensor([2,4,5,6,1,2,24,6,2])
print(f"max : {y.argmax()}")
print(f"min : {y.argmin()}")

"""### Find the mean

"""

torch.mean(y.type(torch.float32))

y.type()

torch.sum(y) ,  y.sum()

"""### Reshaping, Stacking, squeezing and unsqueezing tensors

"""

x = torch.arange(1.,10.)
x ,x.shape

# Add an extra dimension
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

z = x.view(1,9)
z ,z.shape

# Changing z changes x (cause view of a tensor shares the same memort cells)
z[:,0] = 5
x , z

x_stacked = torch.stack([x,x,x,x],dim = 0)
x_stacked

device = "cuda" if torch.cuda.is_available() else "cpu"
device

!nvidia_smi

!nvidia_smi

!nvidia-smi

## Putting tensors on the GPU

# Create a tenoser
tensor = torch.tensor([1,2,3])

print(tensor,tensor.device)

#move tensor to gpu if avaiable

tensor_on_gpu = tensor.to(device)
tensor_on_gpu

### 4.moving tensors back to do cpu

tensor_on_cpu = tensor.cpu()
tensor_on_cpu.numpy()

tensor_on_gpu



