# -*- coding: utf-8 -*-
"""01._PyTorch Workflow Fundamentals.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WIYQ5r2MJS3KNM-fQJfPBg_9Gm4eYarb
"""

import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from torch import nn ## nn contains all of pytorch building blocks of nuerual networks

torch.__version__

"""### PyTorch Worflow


"""

what_were_covering = {1: "data (preapre and load)",
                      2: "build model",
                      3: "fitting the model to date (training)",
                      4: "making predictions and evulating a model (inference)",
                      5: "saving and load a model",
                      6: "putting it al together"}

what_were_covering

"""## Data (Prepairing and Loading)

Machine learning is a game of two parts:
1.Get data into a numerical representation
2.Build a model to learn patterns in that numerical represantation or use pre traning model
Linear reggresion formula to make  a straight line with know paramethers

"""

#Create known paramathers
weight = 0.7
bias = 0.3

# Create
start = 0
end = 1
step = 0.02
X = torch.arange(start,end,step).unsqueeze(dim=1)
y = weight * X + bias

X[:10],y[:10],len(X),len(y)

""" ### Spliting data into training end test sets"""

# Create a train / test split
train_split = int (0.8 * len(X))
X_train ,y_train = X[:train_split],y[:train_split]
X_test,y_test = X[train_split:],y[train_split:]
len(X_train),len(y_train),len(X_test),len(y_test)

"""### Visualize our data"""

def plot_predictions(train_data = X_train,
                     train_labels= y_train,
                     test_data = X_test,
                     test_labels = y_test,
                     predictions = None):
  """
  Plots training data,test data and compares predictions.
  """
  plt.figure(figsize=(10,7))
  # Plot training data in blue
  plt.scatter(train_data,train_labels,c="b",s=4,label = "Traning Data")
  plt.scatter(test_data,test_labels,c = "g", s=4,label = "Testing Data")
  # Are there predictions?
  if predictions is not None:
    # Plot the predictions if they exist
    plt.scatter(test_data,predictions, c="r", s=4,label= "Predictions")
  #Show the legend
  plt.legend(prop={"size": 14})

plot_predictions()

"""## 2. BUİLD MODEL

first pytorch model

What our model does:
Start with random values (weight & bias)


Look at traning data and adjust the random values to better represent(or get closer to)
the ideal values
How deoes it do ?

Through to main algorithms:
1. Gradiant escent
2. Backpropagation
"""

from typing import Required

# Create linear regresiion model class
from torch import nn
class LinearRegressionModel(nn.Module):
  def __init__(self):
    super().__init__()
    self.weights = nn.Parameter(torch.rand(1,
                                               requires_grad=True,
                                               dtype = torch.float))
    self.bias = nn.Parameter(torch.rand(1,
                                         requires_grad=True,
                                         dtype = torch.float))
     # Forward method to define the computation in the model
  def forward(self, x:torch.Tensor) -> torch.Tensor:
        return self.weights * x  + self.bias

""" ## Checking the contents of our PyTorch model



"""

#Create a random seed
torch.manual_seed(42)

# Create instandce of model (this is a subclass of nn.Module)
model_0 = LinearRegressionModel()
list(model_0.parameters())

model_0.state_dict()

weight,bias

"""## Making prediction using "torch.inference_mode()"

To check our model 's predictive power,' lets see how wellit predicts 'y_test based on x_test'

When we pass data through our model run it through the 'forward()' method
"""

# Make predictions with model

with torch.inference_mode(): #Contex manager and helps with gradient in someway
  y_preds = model_0(X_test)

# with torhc.no_grad():  same thing but inference mode makes more thing behinde scnes
#  y_preds = model_0(X_test)

y_preds

y_test

plot_predictions(predictions= y_preds)

"""###Things we need to train:


**Loss Funciton:**
A function to mesaure how wrong your model's predictions are to the ideal output


**Optimizor:** Takes into account the loss of a model and adjust the model paramethers
"""

list(model_0.parameters())

model_0.state_dict()

# Setup a loss function

loss_fn = nn.L1Loss()

# Setup an optimizer (stochastic gradient descent)
optimizer = torch.optim.SGD(params = model_0.parameters(),
                            lr=0.01) #lr = learning rate = Possibly the most important hyperparameter you can set

"""### Building training loop (and a testing loop) in PyTorch

A couple of things we need in a traning loop:

 0. Loop through the data parallel
 1. Forward pass (this involves data moving through our model's forward() functions)
 to make predictions in data
 2. Calculate the loss (compare forward pass predicitons to ground truth labels)
 3. Optimazer zero grad
 4. Loss backward - Move backwards through the network to calculate the gradients of
 each of the parameters of our model with respect to the loss (**backpropagation**)
 5. Optimazer step - use the optimazer to adjust our models parameters to try and improve the loss (**gradient descent**)
"""

list(model_0.eval().parameters())

list(model_0.parameters())

torch.manual_seed(42)

# An epoch is one loop through the data( This is a hyperparameter becuase weve set it ourselvs)
epochs = 10000

#Track diffrent values
epoch_count = []
loss_values = []
test_loss_values = []

## Training
# 0.Loop through the data

for epoch in range(epochs):
    # Set the model to traning mode
    model_0.train()  # Train mode in PyTorch sets all parametesr thath require gradients to require gradiantes

    #1. Forward pass
    y_pred = model_0(X_train)

    #2. Calculate the loss (loss(input,target)
    loss = loss_fn(y_pred,y_train)

    #3. Optimazer zero grad
    optimizer.zero_grad()

    #4. Perform backpropagation on the loss with respect to the parameters of the model
    loss.backward()

    #5. Step the optimizer (perform gradient descent)
    optimizer.step()  # By default how the optimezr changers will acculumate through the loop so... we have to zero then above in the stepvb


    model_0.eval() # turns off diffrent settings in the model not needed for evaluation/testing (dropout / barch norm layers)
    with torch.inference_mode():  # Turns off gradent tracking
        # 1.  Do the forward pass
        test_pred = model_0(X_test)

        #2. Calculate the loss
        test_loss = loss_fn(test_pred,y_test)

    if epoch % 10 == 0:
      epoch_count.append(epoch)
      loss_values.append(loss)
      test_loss_values.append(test_loss)
      print(f"Epoch : {epoch} | Loss : {loss} | Test loss:{test_loss}")
      print(model_0.state_dict())

import numpy as np
np.array(torch.tensor(loss_values).cpu().numpy()),np.array(torch.tensor(test_loss_values).cpu().numpy())

# Plot the loss curves
plt.plot(epoch_count,np.array(torch.tensor(loss_values).cpu().numpy()), label = "Train Loss")
plt.plot(epoch_count,np.array(torch.tensor(test_loss_values).cpu().numpy()),label = " Test Loss")
plt.title("Traning and test loss curves")
plt.ylabel("Loss")
plt.xlabel("Epochs")
plt.legend();

model_0.state_dict()

with torch.inference_mode():
  y_pred_new = model_0(X_test)

with torch.inference_mode():

  plot_predictions(predictions = y_preds_new)

"""### Saving in a model in PyTorch

There a tree main methods you for saving a loading models in PyTorch.

1. Torch.save() - Alloves you save a PyTorch object in Pythons pickle format.
2. Torch.load() - Alloves you to load PyTorch object.
3. Torch.nn.Module.load_state_dict() - This allows to load a model saved state dictionary.

"""

model_0.state_dict()

# Saving our PyTorch model

from pathlib import Path

#1.Create a model directory

MODEL_PATH = Path("models")

MODEL_PATH.mkdir(parents= True, exist_ok = True)

#2.Create model save path

MODEL_NAME = "O1_Pytorch_Workflow_LineerRegrassion_Model.pth"

MODEL_SAVE_PATH = MODEL_PATH / MODEL_NAME

# Save the model state_dict()
print(f"Saving model to {MODEL_SAVE_PATH}")

torch.save(obj =model_0.state_dict(),
           f= MODEL_SAVE_PATH)

!ls -1 models

model_0.state_dict()

"""### Loading PyTorch Model

"""

F# To load in a saved state_dict we have to instantiate a new instance of our model class
loaded_model_0 =LinearRegressionModel()


# Load the saved state_dict() of model_o
loaded_model_0.load_state_dict(torch.load(f= MODEL_SAVE_PATH))


loaded_model_0.state_dict()

loaded_model_0.eval()
with torch.inference_mode():
  loaded_model_preds = loaded_model_0(X_test)
loaded_model_preds

y_preds_new == loaded_model_preds

y_pred_new

